import React, { createContext, useContext, useState, useEffect } from 'react';
import { settingsService } from '../utils/settingsService';

const LanguageContext = createContext(null);

// Simple mock translations for now
const translations = {
  en: {
    'Dashboard': 'Dashboard',
    'Properties': 'Properties',
    'Tenants': 'Tenants',
    'Leases': 'Leases',
    'Payments': 'Payments',
    'Utilities': 'Utilities',
    'Maintenance': 'Maintenance',
    'Documents': 'Documents',
    'Analytics': 'Analytics',
    'English': 'English',
    'Amharic': 'አማርኛ',
    'My Profile': 'My Profile',
    'Settings': 'Settings',
    'Log Out': 'Log Out',
    'Rental Management': 'Rental Management',
    'Login': 'Login',
    'Sign Up': 'Sign Up',
    'Home': 'Home',
    'Features': 'Features',
    'Pricing': 'Pricing',
    'Demo': 'Demo',
    'Contact': 'Contact',
    // Settings page
    'Manage your account preferences and application settings.': 'Manage your account preferences and application settings.',
    'Appearance': 'Appearance',
    'Theme': 'Theme',
    'Light': 'Light',
    'Dark': 'Dark',
    'Regional': 'Regional',
    'Language': 'Language',
    'Business Settings': 'Business Settings',
    'VAT Rate (%)': 'VAT Rate (%)',
    'Withholding Tax Rate (%)': 'Withholding Tax Rate (%)',
    'Business Income Tax Rate (%)': 'Business Income Tax Rate (%)',
    'Account': 'Account',
    'Email Notifications': 'Email Notifications',
    'Push Notifications': 'Push Notifications',
    'Save Settings': 'Save Settings',
    'Saving...': 'Saving...',
    'Settings saved successfully!': 'Settings saved successfully!',
    'Failed to save settings. Please try again.': 'Failed to save settings. Please try again.',
    // Utilities page
    'Track and manage utility bills for all your properties.': 'Track and manage utility bills for all your properties.',
    'Add Utility Bill': 'Add Utility Bill',
    'Search by type or property...': 'Search by type or property...',
    'Type': 'Type',
    'Property': 'Property',
    'Amount': 'Amount',
    'Due Date': 'Due Date',
    'Status': 'Status',
    'Actions': 'Actions',
    'Electricity': 'Electricity',
    'Water': 'Water',
    'Gas': 'Gas',
    'Internet': 'Internet',
    'Trash': 'Trash',
    'Other': 'Other',
    'Select Type': 'Select Type',
    'Select Property': 'Select Property',
    'Amount ($)': 'Amount ($)',
    'Unpaid': 'Unpaid',
    'Paid': 'Paid',
    'Bill Image': 'Bill Image',
    'No image selected': 'No image selected',
    'Selected: ': 'Selected: ',
    'No Utility Bills Found': 'No Utility Bills Found',
    'Get started by adding a new utility bill.': 'Get started by adding a new utility bill.',
    'Utility Type': 'Utility Type',
    // Leases page
    'Lease Agreements': 'Lease Agreements',
    'Manage all active, expired, and upcoming leases.': 'Manage all active, expired, and upcoming leases.',
    'Add Lease': 'Add Lease',
    'Search by tenant, property, or unit...': 'Search by tenant, property, or unit...',
    'Tenant': 'Tenant',
    'Property / Unit': 'Property / Unit',
    'Lease Period': 'Lease Period',
    'Withholding': 'Withholding',
    'Rent': 'Rent',
    'N/A': 'N/A',
    'Unit': 'Unit',
    'No Lease': 'No Lease',
    'Expired': 'Expired',
    'Active': 'Active',
    'Upcoming': 'Upcoming',
    'View Details': 'View Details',
    'Edit': 'Edit',
    'Renew': 'Renew',
    'Delete': 'Delete',
    'Lease Details: ': 'Lease Details: ',
    'Lease & Property': 'Lease & Property',
    'Period': 'Period',
    'Financials': 'Financials',
    'Monthly Rent': 'Monthly Rent',
    'Lease Documents': 'Lease Documents',
    'Lease Agreement': 'Lease Agreement',
    'Withholding Receipt': 'Withholding Receipt',
    'Not provided': 'Not provided',
    'Close': 'Close',
    'Add New Lease': 'Add New Lease',
    'Renew Lease': 'Renew Lease',
    'Edit Lease': 'Edit Lease',
    'Select a tenant': 'Select a tenant',
    'Select a property': 'Select a property',
    'Select a unit': 'Select a unit',
    'Lease Start Date': 'Lease Start Date',
    'Lease End Date': 'Lease End Date',
    'Monthly Rent (ETB)': 'Monthly Rent (ETB)',
    'Withholding Amount (Optional)': 'Withholding Amount (Optional)',
    'Upload PDF or image': 'Upload PDF or image',
    'Save Lease': 'Save Lease',
    'No Leases Found': 'No Leases Found',
    'Get started by adding a new lease agreement.': 'Get started by adding a new lease agreement.',
    // Analytics page
    'Analytics & Reports': 'Analytics & Reports',
    'Visualize your portfolio\'s financial performance.': 'Visualize your portfolio\'s financial performance.',
    'Export as PDF': 'Export as PDF',
    'Start Date': 'Start Date',
    'End Date': 'End Date',
    'All Properties': 'All Properties',
    'Generating...': 'Generating...',
    'Generate Report': 'Generate Report',
    'Total Revenue': 'Total Revenue',
    'Total Expenses': 'Total Expenses',
    'Net Profit': 'Net Profit',
    'Estimated Tax': 'Estimated Tax',
    'Loading analytics data...': 'Loading analytics data...',
    'No data available for this period': 'No data available for this period',
    'Monthly Profit & Loss': 'Monthly Profit & Loss',
    'Income by Property': 'Income by Property',
    'Expense Breakdown': 'Expense Breakdown',
    'Financial Summary': 'Financial Summary',
    'Income Sources': 'Income Sources',
    'Total Income': 'Total Income',
    'Expense Categories': 'Expense Categories',
    'Analytics Total Expenses': 'Analytics Total Expenses',
    'Profitability': 'Profitability',
    'Tax Summary': 'Tax Summary',
    'VAT Payable': 'VAT Payable',
    'Business Income Tax': 'Business Income Tax',
    'Withholding Tax': 'Withholding Tax',
    'Total Tax Liability': 'Total Tax Liability',
    'Transactions': 'Transactions',
    'Date': 'Date',
    'Transaction Description': 'Transaction Description',
    'Category': 'Category',
    'Transaction Type': 'Transaction Type',
    'Transaction Amount': 'Transaction Amount',
    'Recorded By': 'Recorded By',
    'No transactions available': 'No transactions available',
    'Tax Summary Table': 'Tax Summary Table',
    'Tax Summary Tax Type': 'Tax Summary Tax Type',
    'Tax Period': 'Tax Period',
    'Pending': 'Pending',
    'Estimated': 'Estimated',
    'Tracked': 'Tracked',
    'Audit Log': 'Audit Log',
    'Timestamp': 'Timestamp',
    'User': 'User',
    'Action': 'Action',
    'Entity': 'Entity',
    'Details': 'Details',
    'No audit log available': 'No audit log available',
    // Documents page
    'Manage all your important documents in one place.': 'Manage all your important documents in one place.',
    'Upload Document': 'Upload Document',
    'Search by document name...': 'Search by document name...',
    'All Agreements': 'All Agreements',
    'Document Lease Agreements': 'Document Lease Agreements',
    'Receipts': 'Receipts',
    'Tax Documents': 'Tax Documents',
    'Others': 'Others',
    'Name': 'Name',
    'Linked To': 'Linked To',
    'Size': 'Size',
    'Upload Date': 'Upload Date',
    'View': 'View',
    'Download': 'Download',
    'No Documents Found': 'No Documents Found',
    'Get started by uploading a new document.': 'Get started by uploading a new document.',
    // Profile page
    'Manage your account information and preferences.': 'Manage your account information and preferences.',
    'Edit Profile': 'Edit Profile',
    'Save': 'Save',
    'Cancel': 'Cancel',
    'Full Name': 'Full Name',
    'Email Address': 'Email Address',
    'Phone Number': 'Phone Number',
    'Address': 'Address',
    'Change Avatar': 'Change Avatar',
    'Profile updated successfully!': 'Profile updated successfully!',
    'Failed to update profile. Please try again.': 'Failed to update profile. Please try again.',
    'Please log in to view your profile.': 'Please log in to view your profile.',
    'Account Actions': 'Account Actions',
    'Change Password': 'Change Password',
    'Logout': 'Logout',
    // Maintenance page
    'Maintenance Requests': 'Maintenance Requests',
    'Track and manage all maintenance tasks.': 'Track and manage all maintenance tasks.',
    'Add Request': 'Add Request',
    'Search by title, property, or status...': 'Search by title, property, or status...',
    'Title': 'Title',
    'Reported Date': 'Reported Date',
    'Cost': 'Cost',
    'In Progress': 'In Progress',
    'Completed': 'Completed',
    'No Maintenance Requests': 'No Maintenance Requests',
    'Get started by adding a new maintenance request.': 'Get started by adding a new maintenance request.',
    'Add Maintenance Request': 'Add Maintenance Request',
    'Request Title': 'Request Title',
    'Estimated Cost ($)': 'Estimated Cost ($)',
    // Dashboard page
    'Loading your rental overview...': 'Loading your rental overview...',
    'Loading...': 'Loading...',
    'Welcome back, here\'s your rental overview.': 'Welcome back, here\'s your rental overview.',
    'Total Properties': 'Total Properties',
    'Active Tenants': 'Active Tenants',
    'Monthly Revenue': 'Monthly Revenue',
    'Outstanding Balance': 'Outstanding Balance',
    'Recent Activity': 'Recent Activity',
    'Activity': 'Activity',
    'Tenants Page Tenant': 'Tenants Page Tenant',
    'Transaction Date': 'Transaction Date',
    'No recent activity.': 'No recent activity.',
    'New Tenant Added': 'New Tenant Added',
    'Quick Actions': 'Quick Actions',
    'Properties Add Property': 'Properties Add Property',
    'Add Tenant': 'Add Tenant',
    'Record Payment': 'Record Payment',
    'Upcoming Lease Expirations': 'Upcoming Lease Expirations',
    'No leases are expiring in the next 60 days.': 'No leases are expiring in the next 60 days.',
    'Failed to load dashboard data. Please try again.': 'Failed to load dashboard data. Please try again.',
    'Retry': 'Retry',
    // Properties page
    'View and manage all your properties': 'View and manage all your properties',
    'Add Property': 'Add Property',
    'Search by name or address...': 'Search by name or address...',
    'Total Units:': 'Total Units:',
    'Default Monthly Rent': 'Default Monthly Rent',
    'No properties found': 'No properties found',
    'Get started by adding a new property.': 'Get started by adding a new property.',
    'Add New Property': 'Add New Property',
    'Property Name': 'Property Name',
    'Property Address': 'Property Address',
    'Property Type': 'Property Type',
    'Default Monthly Rent (ETB)': 'Default Monthly Rent (ETB)',
    'Property Tax Type': 'Property Tax Type',
    'Property Tax': 'Property Tax',
    'Withholding + Annual': 'Withholding + Annual',
    'Withholding + Property': 'Withholding + Property',
    'All Taxes': 'All Taxes',
    'Description': 'Description',
    'Property Image': 'Property Image',
    'Property No Image Selected': 'Property No Image Selected',
    'Units': 'Units',
    'Unit Number': 'Unit Number',
    'Floor': 'Floor',
    'Bedrooms': 'Bedrooms',
    'Bathrooms': 'Bathrooms',
    'Size (sq ft)': 'Size (sq ft)',
    'Rent (ETB)': 'Rent (ETB)',
    'Notes': 'Notes',
    'Unit Image': 'Unit Image',
    'Remove Unit': 'Remove Unit',
    'Add Unit': 'Add Unit',
    'Properties Cancel': 'Properties Cancel',
    'No image': 'No image',
    'Edit Progress': 'Edit Progress',
    'Update Progress': 'Update Progress',
    'Progress': 'Progress',
    'Select Status': 'Select Status',
    "Back to Requests": "Back to Requests",
    "Maintenance Request Details": "Maintenance Request Details",
    "View comprehensive information for this maintenance task.": "View comprehensive information for this maintenance task.",
    "Share": "Share",
    "Print": "Print",
"Request Information": "Request Information",
"Date Reported": "Date Reported",
    "Financials & Receipt": "Financials & Receipt",
"Receipt Number": "Receipt Number",
"Attachments": "Attachments",
    "Loading maintenance requests...": "Loading maintenance requests...",
    "Monthly": "Monthly",
    "Annual": "Annual",
"As Incurred": "As Incurred",
"Total Collected": "Total Collected",
    "Total Overdue Amount": "Total Overdue Amount",
    "Overdue Payments": "Overdue Payments",
    "Search by tenant or property...": "Search by tenant or property...",

    "Reports": "Reports",
    "Filter by property": "Filter by property",
    "Show All": "Show All",
  },
  am: {
    'Dashboard': 'ዳሽቦርድ',
    'Properties': 'ንብረቶች',
    'Tenants': 'ተከራዮች',
    'Leases': 'ኪራዮች',
    'Payments': 'ክፍያዎች',
    'Utilities': 'መገልገያዎች',
    'Maintenance': 'ጥገና',
    'Documents': 'ሰነዶች',
    'Analytics': 'ትንታኔዎች',
    'English': 'እንግሊዝኛ',
    'Amharic': 'አማርኛ',
    'My Profile': 'የእኔ መገለጫ',
    'Settings': 'ቅንብሮች',
    'Log Out': 'ውጣ',
    'Rental Management': 'የኪራይ አስተዳደር',
    'Login': 'ግባ',
    'Sign Up': 'ተመዝገብ',
    'Home': 'መነሻ',
    'Features': 'ባህሪያት',
    'Pricing': 'ዋጋ',
    'Demo': 'ማሳያ',
    'Contact': 'አግኙን',
    'Yene Rent': 'የኔ ኪራይ',
    // Testimonials
    'This rental management system has transformed how I handle my properties. The tax automation alone saves me hours every month, and the Ethiopian compliance features are spot-on!': 'የኪራይ አስተዳደር ስርዓት ንብረቶቼን እንዴት እንደማስተዳድር ለወጡአል። የግብር ራህደን ብቻ በወር ለሰዓታት ያስቀምጣል፣ እና የኢትዮጵያ ተስማማት ባህሪያት ትክክለኛ ናቸው!',
    'Managing 15 properties used to be a nightmare. Now everything is centralized, easy to access, and I have real-time insights. Highly recommend for any property owner!': '15 ንብረቶችን ለማስተዳደር እስካሁን አስቸጋሪ ነበር። አሁን ሁሉም ነገር ማዕከላዊ ነው፣ ቀላል ለመስበክ እና በተግዛት ጊዜ እይታዎች አሉኝ። ለማንኛውም ንብረት ባለቤት በጣም እመክራለሁ!',
    'The financial analytics are incredible. I can now track profitability across all my units and make data-driven decisions. The reporting features are exactly what I needed.': 'የገንዘብ ትንታኔዎች እንግዳ ናቸው። አሁን በሁሉም ክፍሎቼ ላይ ለምንድነት መከታተል እና በውሂብ ላይ የሚተያዩ ውሳኔዎችን ለማስተላለፍ እችላለሁ። የሪፖርት ባህሪያት ትክክለኛ ያህል ነው ያስፈልገኝ ነበር።',
    'As a landlord with multiple tenants, the tenant management tools have been a game-changer. Lease tracking, payment reminders, and document storage all in one place.': 'ባህላዊ ተከራዮች ያሉት እንደ ኪራይ ባለቤት፣ የተከራይ አስተዳደር መሣሪያዎች ለውጥ አስተያየት ናቸው። ኪራይ መከታተያ፣ የክፍያ ማሳወቂያዎች እና የሰነድ ማከማቻ ሁሉ በአንድ ቦታ።',
    // Login/Signup
    'Rental System': 'የኪራይ ስርዓት',
    'Sign in to manage your properties': 'ንብረቶችዎን ለማስተዳደር ግባ',
    'Email Address': 'የኢሜይል አድራሻ',
    'Password': 'የይለፍ ቃል',
    'Forgot your password?': 'የይለፍ ቃልዎን ረሱት?',
    'Sign In': 'ግባ',
    'Don\'t have an account? Sign up': 'መለያ የለዎትም? ተመዝገብ',
    'Create your account': 'መለያዎን ይፍጠሩ',
    'Full Name': 'ሙሉ ስም',
    'Confirm Password': 'የይለፍ ቃል ያረጋግጡ',
    'Already have an account? Sign in': 'መለያ አለዎት? ግባ',
    'Signup Sign Up': 'ተመዝገብ',
    // Payments page
    'Payment Schedule': 'የክፍያ መርሃግብር',
    'Track all scheduled, paid, and overdue rent payments.': 'ሁሉንም የተርሃገሩ፣ የተስተካከሉ እና ያልተስተካከሉ የኪራይ ክፍያዎችን ያከታተሉ።',
    'Total Collected': 'ጠቅላላ የተሰበሰበ',
    'This Month': 'በዚህ ወር',
    'Total Overdue Amount': 'ጠቅላላ ያልተስተካከለ መጠን',
    'Overdue Payments': 'ያልተስተካከሉ ክፍያዎች',
    'Search by tenant or property...': 'በተከራይ ወይም ንብረት ያስሱ...',
    'Due Date': 'የሚሆንበት ቀን',
    'Amount': 'መጠን',
    'Receipt': 'የክፍያ ማሳያ',
    'No Payments Found': 'ምንም ክፍያዎች አልተለመዱም',
    'Get started by recording a new payment.': 'አዲስ ክፍያ በመመዝገብ ያስጀምሩ።',
    // Settings page
    'Manage your account preferences and application settings.': 'የመለያ ምርጫዎችን እና የመተግበሪያ ቅንብሮችን ያስተዳድሩ።',
    'Appearance': 'መልክ',
    'Theme': 'ገጽታ',
    'Light': 'ብርሃን',
    'Dark': 'ጥሩ',
    'Regional': 'ክልላዊ',
    'Language': 'ቋንቋ',
    'Business Settings': 'የንግድ ቅንብሮች',
    'VAT Rate (%)': 'የቫት ተመን (%)',
    'Withholding Tax Rate (%)': 'የማያወጣ ግብር ተመን (%)',
    'Business Income Tax Rate (%)': 'የንግድ ገቢ ግብር ተመን (%)',
    'Account': 'መለያ',
    'Email Notifications': 'የኢሜይል ማሳወቂያዎች',
    'Push Notifications': 'የመላክ ማሳወቂያዎች',
    'Save Settings': 'ቅንብሮችን አስቀምጥ',
    'Saving...': 'በማስቀመጥ ላይ...',
    'Settings saved successfully!': 'ቅንብሮች በተሳካ መልክ ተስተያዩ!',
    'Failed to save settings. Please try again.': 'ቅንብሮችን ለማስቀመጥ አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    // Dashboard page
    'Loading your rental overview...': 'የኪራይ አጠቃላይ እይታን በመጫን ላይ...',
    'Loading...': 'በመጫን ላይ...',
    'Welcome back, here\'s your rental overview.': 'እንደገና እንኳን ደህና መጡ፣ የኪራይ አጠቃላይ እይታ እነሆ።',
    'Total Properties': 'ጠቅላላ ንብረቶች',
    'Active Tenants': 'ንቁ ተከራዮች',
    'Monthly Revenue': 'የወር ገቢ',
    'Outstanding Balance': 'ያልተስተካከለ ቀሪ ሂሳብ',
    'Recent Activity': 'የቅርቡ ተግባር',
    'Activity': 'ተግባር',
    'Tenant': 'ተከራይ',
    'Date': 'ቀን',
    'No recent activity.': 'የቅርቡ ተግባር የለም።',
    'New Tenant Added': 'አዲስ ተከራይ ተጨምሯል',
    'Quick Actions': 'ፈጣን ተግባራት',
    'Add Property': 'ንብረት ጨምር',
    'Dashboard Add Tenant': 'ተከራይ ጨምር',
    'Record Payment': 'ክፍያ ያስተያዩ',
    'Upcoming Lease Expirations': 'የሚመጡ ኪራይ ማብቂያዎች',
    'No leases are expiring in the next 60 days.': 'በሚቀጥለው 60 ቀናት ውስጥ ምንም ኪራይ አያብቅም።',
    'Failed to load dashboard data. Please try again.': 'የዳሽቦርድ ውሂብ መጫን አልተሳካም። እባክዎ እንደገና ይሞክሩ።',
    'Retry': 'እንደገና ሞክር',
    // Properties page
    'View and manage all your properties': 'ንብረቶችዎን ሁሉ ይመልክቱ እና ያስተዳድሩ',
    'Search by name or address...': 'በስም ወይም በአድራሻ ያስሱ...',
    'Total Units:': 'ጠቅላላ ክፍሎች:',
    'Default Monthly Rent': 'ነባሪ የወር ኪራይ',
    'No properties found': 'ምንም ንብረቶች አልተለመዱም',
    'Get started by adding a new property.': 'አዲስ ንብረት በመጨመር ያስጀምሩ።',
    'Add New Property': 'አዲስ ንብረት ጨምር',
    'Property Name': 'የንብረት ስም',
    'Address': 'አድራሻ',
    'Property Type': 'የንብረት አይነት',
    'Default Monthly Rent (ETB)': 'ነባሪ የወር ኪራይ (ETB)',
    'Tax Type': 'የግብር አይነት',
    'Property Tax': 'የንብረት ግብር',
    'Withholding + Annual': 'ማያወጣ + ዓመታዊ',
    'Withholding + Property': 'ማያወጣ + ንብረት',
    'All Taxes': 'ሁሉም ግብሮች',
    'Description': 'መግለጫ',
    'Property Image': 'የንብረት ምስል',
    'No image selected': 'ምንም ምስል አልተለመደም',
    'Units': 'ክፍሎች',
    'Unit Number': 'የክፍል ቁጥር',
    'Floor': 'ወለል',
    'Bedrooms': 'የእንቅልፍ ቦታዎች',
    'Bathrooms': 'የመታጠቢያ ቦታዎች',
    'Size (sq ft)': 'መጠን (sq ft)',
    'Rent (ETB)': 'ኪራይ (ETB)',
    'Notes': 'ማስታወሻዎች',
    'Unit Image': 'የክፍል ምስል',
    'Remove Unit': 'ክፍል አስወግድ',
    'Add Unit': 'ክፍል ጨምር',
    'Cancel': 'ሰርዝ',
    'No image': 'ምስል የለም',
    // Tenants page
    'Manage all tenants across your properties.': 'ንብረቶችዎ ሁሉ ላይ ተከራዮችን ያስተዳድሩ።',
    'Add Tenant': 'ተከራይ ጨምር',
    'Search by name, email, or property...': 'በስም፣ ኢሜይል ወይም ንብረት ያስሱ...',
    'Name': 'ስም',
    'Tenants Contact': 'የመገናኛ መረጃ',
    'Property / Unit': 'ንብረት / ክፍል',
    'Lease Period': 'ኪራይ ጊዜ',
    'TIN Number': 'ቲን ቁጥር',
    'Status': 'ሁኔታ',
    'Actions': 'ተግባራት',
    'No Tenants Found': 'ምንም ተከራዮች አልተለመዱም',
    'Unit': 'ክፍል',
    'N/A': 'አይተገናኘም',
    'No Lease': 'ኪራይ የለም',
    'Expired': 'ጊዜ አልፏል',
    'Active': 'ንቁ',
    'Upcoming': 'የሚመጣ',
    'View Details': 'ዝርዝሮችን ይመልክቱ',
    'Edit': 'አርትዕ',
    'Delete': 'ሰርዝ',
    // Landing Page
    'Simplify Rental Management — Track, Analyze, and Automate with Ease': 'የኪራይ አስተዳደርን ያሳርፉ — ያከታተሉ፣ ያስተናግዱ እና በቀላሉ ያአውታማውቁ',
    'Manage your entire rental property portfolio effortlessly. Our system provides powerful tools for tenant management, financial tracking, and automated tax reporting compliant with Ethiopian rules.': 'የኪራይ ንብረት ፖርትፎሊዮን ሁሉ በቀላሉ ያስተዳድሩ። ስርዓታችን ለተከራዮች አስተዳደር፣ የገንዘብ መከታተያ እና ከኢትዮጵያ ህጎች ጋር የሚስማማ ያልተለመደ የግብር ሪፖርት ለማድረግ ኃይለኛ መሣሪያዎችን ያቀርባል።',
    'Try Demo': 'ዲሞ ይሞክሩ',
    'Request a Free Trial': 'ነጻ ሙከራ ይጠይቁ',
    'Core System Capabilities 🛠️': 'የስርዓት ዋና ችሎታዎች 🛠️',
    'Property & Tenant Management': 'ንብረት እና ተከራይ አስተዳደር',
    'Manage your entire portfolio from one comprehensive dashboard, including leases and tenant records.': 'ኪራዮችን እና የተከራዮች መዝገቦችን ጨምሮ ፖርትፎሊዮን ሁሉ ከአንድ ሁሉን አቀፍ ዳሽቦርድ ያስተዳድሩ።',
    'Financial Analytics': 'የገንዘብ ትንታኔዎች',
    'Track income, expenses, and profitability in real-time with insightful visual reports.': 'ገቢ፣ ወጪዎች እና ለምንድነትን በተግዛት ጊዜ በተለመዱ ምስል ሪፖርቶች ያከታተሉ።',
    'Tax Automation': 'የግብር ራህደን',
    'Handle Ethiopian tax rules automatically, ensuring compliance and accurate reporting.': 'የኢትዮጵያ ግብር ህጎችን በራህደን ያስተዳድሩ፣ ተስማማት እና ትክክለኛ ሪፖርት ያረጋግጡ።',
    'Smart Reporting': 'ብልህ ሪፖርት',
    'Export financial summaries and operational reports with a single, quick click.': 'የገንዘብ ማጠቃለያዎችን እና የስራ ሪፖርቶችን በአንድ ፈጣን ጠቅታ ያስተላልፉ።',
    'Document Management': 'የሰነድ አስተዳደር',
    'Upload, organize, and securely access all your important property and tenant files in one place.': 'አስፈላጊ ንብረት እና የተከራይ ፋይሎችን ሁሉ በአንድ ቦታ ያስተላልፉ፣ ያደራጁ እና በደህንነት ያስተያዩ።',
    'Security & Compliance': 'ደህንነት እና ተስማማት',
    'Enterprise-grade security and full data compliance to protect sensitive information.': 'የኢንተርፕራይዝ ደረጃ ደህንነት እና ሙሉ ውሂብ ተስማማት ለሚስጠራ መረጃ ለመጠበቅ።',
    'Deep Dive into Our Modules 🔍': 'ወደ ሞዱሎች በጥልቀት ያስተያዩ 🔍',
    'Comprehensive Dashboard & Core Management': 'ሁሉን አቀፍ ዳሽቦርድ እና ዋና አስተዳደር',
    'Get a bird\'s-eye view of your portfolio with actionable insights and quick links to core management functions. Effortlessly manage property details, unit assignments, and tenant lifecycle.': 'የፖርትፎሊዮን አጠቃላይ እይታ ከሊቀ ተግባራት እና ወደ ዋና አስተዳደር ተግባራት ፈጣን አገናኞች ጋር ያግኙ። የንብረት ዝርዝሮችን፣ የክፍል ምደባዎችን እና የተከራይ ህይወት በቀላሉ ያስተዳድሩ።',
    'Learn More &rarr;': 'ተጨማሪ ያስተማሩ &rarr;',
    'Financial Analytics & Reporting': 'የገንዘብ ትንታኔዎች እና ሪፖርት',
    'Visualize your cash flow, identify profit drivers, and minimize losses with our advanced, integrated financial tools and customizable reporting suite.': 'የገንዘብ ፍሰትን ያሳዩ፣ የለምንድነት አስተያየቶችን ያለዩ እና በላይ ያሉ የገንዘብ መሣሪያዎች እና ሊለወጡ የሚችሉ ሪፖርት ስብስቦች በመርገጥ በጉድለቶችን ያሳንሱ።',
    'See Our System in Action 🎬': 'ስርዓታችንን በተግባር ያዩ 🎬',
    'See how it works — Explore the Demo': 'እንዴት እንደሚሰራ ያዩ — ዲሞን ያስሱ',
    'Clear & Flexible Pricing 💰': 'አጭር እና ሊለወጡ የሚችሉ ዋጋዎች 💰',
    'Basic': 'መሰረታዊ',
    'ETB 1499 / month': 'ETB 1499 / በወር',
    'Single Property Management': 'ነጠላ ንብረት አስተዳደር',
    'Basic Financial Tracking': 'መሰረታዊ የገንዘብ መከታተያ',
    'Tax Automation (Add-on)': 'የግብር ራህደን (ተጨማሪ)',
    'Dedicated Support': 'ልዩ ድጋፍ',
    'Get Started': 'ያስጀምሩ',
    'Professional': 'ሙያዊ',
    'Most Popular': 'ብዙ የሚወዱት',
    'ETB 3999 / month': 'ETB 3999 / በወር',
    'Up to 20 Properties': 'እስከ 20 ንብረቶች',
    'Advanced Analytics & Reporting': 'ላይ ያሉ ትንታኔዎች እና ሪፖርት',
    'Priority Email Support': 'ቅድሚያ ኢሜይል ድጋፍ',
    'Start Trial': 'ሙከራ ያስጀምሩ',
    'Enterprise': 'ኢንተርፕራይዝ',
    'Contact Us': 'እኛን ያግኙ',
    'Unlimited Properties': 'ያልተወሰኑ ንብረቶች',
    'Custom Integrations': 'ሊለወጡ የሚችሉ ውህደቶች',
    'Dedicated Account Manager': 'ልዩ የመለያ አስተዳዳሪ',
    'SLA & 24/7 Support': 'SLA እና 24/7 ድጋፍ',
    'Contact Sales': 'ሽያጭ ያግኙ',
    'Compare All Plans in Detail &rarr;': 'ሁሉንም እቅዶች በዝርዝር ያወዳድሩ &rarr;',
    'Trusted by Property Owners Across Ethiopia ⭐': 'በኢትዮጵያ ሁሉ በንብረት ባለቤቶች የሚተማመኑ ⭐',
    'Frequently Asked Questions ❓': 'ብዙ ጊዜ የሚነሱ ጥያቄዎች ❓',
    'Can I use the system offline?': 'ስርዓትን ከበይነመረብ ያለ መስራት እችላለሁ?',
    'No, the system is cloud-based for real-time data sync and security, requiring an internet connection to access. However, some reporting data can be exported and viewed offline.': 'አይ፣ ስርዓት ለተግዛት ጊዜ ውሂብ ማመሳሰል እና ደህንነት የክላውድ ስርዓት ነው፣ ለመስበክ የበይነመረብ ግንኙነት ያስፈልገዋል። ሆኖም አንዳንድ የሪፖርት ውሂብ ሊለቀ እና ከበይነመረብ ያለ ሊታይ ይችላል።',
    'Is it compatible with Ethiopian tax rules?': 'ከኢትዮጵያ ግብር ህጎች ጋር የሚስማማ ነው?',
    'Absolutely. Our system is specifically engineered to handle all relevant Ethiopian tax laws and reporting requirements automatically.': 'በእኍን ተነጠለ። ስርዓታችን ሁሉንም አስፈላጊ የኢትዮጵያ ግብር ህጎች እና የሪፖርት ፈጣሪያዎችን በራህደን ለማስተዳደር በተለይ ተሰራ።',
    'Do you offer multi-user access?': 'ባህላዊ ተጠቃሚ መስበክ ያቀርባሉ?',
    'Yes, multi-user access with role-based permissions is available on our Professional and Enterprise plans, perfect for teams and businesses.': 'አዎ፣ በሚተያዩ ሚናዎች ላይ የሚተያዩ ባህላዊ ተጠቃሚ መስበክ በሙያዊ እና ኢንተርፕራይዝ እቅዶች ላይ ይገኛል፣ ለቡድኖች እና ንግዶች እንጂ ፍጹም ነው።',
    'What security measures are in place to protect my data?': 'ውሂቤን ለመጠበቅ ምን የደህንነት እርምጃዎች አሉ?',
    'We use end-to-end encryption, multi-factor authentication, and secure cloud hosting to ensure your sensitive property and tenant data is always protected.': 'የእኛ ሚስጠራ ንብረት እና የተከራይ ውሂብ ሁልጊዜ እንዲተጠበቅ ለማረጋገጥ ከጫና እስካም ጫና ምስጠራ፣ ባህላዊ ምክንያት ማረጋገጫ እና የደህንነት ክላውድ ሆስት እንጠቀማለን።',
    // Missing Analytics & Maintenance components
    'Estimated Cost': 'ግምታዊ ወጪ',
    'Edit Progress': 'ሂደቱን አርትዕ',
    'Update Progress': 'ሂደቱን አዘምን',
    'Progress': 'ሂደት',
    'Select Status': 'ሁኔታ ይምረጡ',
    "Back to Requests": "ወደ ጥያቄዎች ይመለሱ",
    "Maintenance Request Details": "የጥገና ጥያቄ ዝርዝሮች",
    "View comprehensive information for this maintenance task.": "ለዚህ የጥገና ሥራ የተሟላ መረጃ ይመልከቱ።",
    "Share": "አጋራ",
    "Print": "አትም",
    "Request Information": "የጥያቄ መረጃ",
    "Request Title": "የጥያቄ ርዕስ",
    "Date Reported": "ሪፖርት የተደረገበት ቀን",
    "Financials & Receipt": "ፋይናንስ እና ደረሰኝ",
"Receipt Number": "የደረሰኝ ቁጥር",
"Attachments": "አባሪዎች",
    "Loading maintenance requests...": "የጥገና ጥያቄዎችን በመጫን ላይ...",
    "Monthly": "ወርሃዊ",
    "Annual": "ዓመታዊ",
    "As Incurred": "እንደተከሰተ",
    "Tracked": "ተከታትሏል",
    "Estimated": "ተገምቷል",
    "Reports": "ሪፖርቶች",
    "Filter by property": "በንብረት ያጣሩ",
    "Show All": "ሁሉንም አሳይ",
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const savedSettings = settingsService.getSettings();
    return savedSettings.regional.language || 'en';
  });

  useEffect(() => {
    // Update settings in localStorage when language changes
    const currentSettings = settingsService.getSettings();
    settingsService.saveSettings({
      ...currentSettings,
      regional: { ...currentSettings.regional, language: language },
    });
  }, [language]);

  const setLanguage = (lang) => {
    setLanguageState(lang);
  };

  const t = (key) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// eslint-disable-next-line react-refresh/only-export-components
export const useLanguage = () => {
  return useContext(LanguageContext);
};
